name: CI build

on:
  push:
    branches: [ feat-fetch-pin-sha256 ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    uses: ./.github/workflows/build.yml
    with:
      target: windows
      project: ./v2rayN/v2rayN.csproj

  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      target: linux

  build-osx:
    uses: ./.github/workflows/build.yml
    with:
      target: macos
